services:
  meilisearch:
    image: getmeili/meilisearch:v1.8
    container_name: meilisearch
    environment:
      - MEILI_NO_ANALYTICS=true
      - MEILI_ENV=${MEILI_ENV}
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
      - MEILI_TASK_WEBHOOK_URL=${MEILI_TASK_WEBHOOK_URL}        # e.g. http://host.docker.internal:8787/api/webhooks/meilisearch
      - MEILI_TASK_WEBHOOK_SECRET=${MEILI_TASK_WEBHOOK_SECRET}
      - MEILI_TASK_WEBHOOK_AUTHORIZATION_HEADER=${MEILI_TASK_WEBHOOK_AUTHORIZATION_HEADER} # e.g. bearer_fake_token
      - MEILI_LOG_LEVEL=DEBUG
    ports:
      - "7700:7700"
    restart: unless-stopped
    volumes:
      - meili_data:/meili_data
    extra_hosts:
      - "host.docker.internal:host-gateway"       # Docker ≥ 20.10

  meilisearch-ui:
    image: riccoxie/meilisearch-ui:latest
    container_name: meilisearch-ui
    ports:
      - "24900:24900"
    restart: unless-stopped
    depends_on:
      - meilisearch
    environment:
      - MEILISEARCH_HOST=${MEILI_SEARCH_HOST}     # http://meilisearch:7700
      - MEILISEARCH_API_KEY=${MEILI_MASTER_KEY}

volumes:
  meili_data: